# main configuration file for the Spring Boot application
spring.application.name=spring_thymeleaf
# man könnte server.port=9090 setzen, damit der Server auf Port 9090 läuft,
# aber das ist nicht nötig, da 8080 der Standardport ist
